import Teacher from '#models/Teacher'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    // Write your database queries inside the run method

    await Teacher.createMany([
      {
        id : 1,
        school_id : 1,
        staff_role_id: 2,
        first_name: "Rita",
        middle_name: "Hitesh",
        last_name: "Patel",
        first_name_in_guj: "રિતા",
        middle_name_in_guj: "હિતેશ",
        last_name_in_guj: "પટેલ",
        gender: "Female",
        birth_date: new Date('1988-03-14'),
        mobile_number: 9876543210,
        email: "rita.patel@example.com",
        qualification: "M.Sc. Physics",
        subject_specialization: "Physics",
        class_id: 4,
        joining_date: new Date('2015-06-15'),
        employment_status: "Permanent",
        aadhar_no: 567890123456,
        religiion: "Hindu",
        religiion_in_guj: "હિન્દુ",
        caste: "Patel",
        caste_in_guj: "પટેલ",
        category: "OPEN",
        address: "12 Green Park",
        district: "Ahmedabad",
        city: "Ahmedabad",
        state: "Gujarat",
        postal_code: 380015,
        bank_name: "Bank of Baroda",
        account_no: 567890123456,
        IFSC_code: "BARB0AHMEDB"
      },
      {
        id : 2,
        school_id : 1,
        staff_role_id: 3,
        first_name: "Kiran",
        middle_name: "Mahesh",
        last_name: "Trivedi",
        first_name_in_guj: "કિરણ",
        middle_name_in_guj: "મહેશ",
        last_name_in_guj: "ત્રિવેદી",
        gender: "Male",
        birth_date: new Date('1985-05-27'),
        mobile_number: 9123456780,
        email: "kiran.trivedi@example.com",
        qualification: "M.A. Geography",
        subject_specialization: "Geography",
        class_id: 7,
        joining_date: new Date('2017-09-12'),
        employment_status: "Permanent",
        aadhar_no: 678901234567,
        religiion: "Hindu",
        religiion_in_guj: "હિન્દુ",
        caste: "Brahmin",
        caste_in_guj: "બ્રાહ્મણ",
        category: "OPEN",
        address: "34 Sunrise Apartments",
        district: "Surat",
        city: "Surat",
        state: "Gujarat",
        postal_code: 395007,
        bank_name: "HDFC Bank",
        account_no: 678901234567,
        IFSC_code: "HDFC0001234"
      },
      {
        id : 3,
        school_id : 1,
        staff_role_id: 3,
        first_name: "Nita",
        middle_name: "Jignesh",
        last_name: "Gandhi",
        first_name_in_guj: "નીતા",
        middle_name_in_guj: "જિગ્નેશ",
        last_name_in_guj: "ગાંધિ",
        gender: "Female",
        birth_date: new Date('1992-08-16'),
        mobile_number: 9988776654,
        email: "nita.gandhi@example.com",
        qualification: "B.Ed. Science",
        subject_specialization: "Science",
        class_id: 6,
        joining_date: new Date('2019-11-20'),
        employment_status: "Trial_period",
        aadhar_no: 789012345678,
        religiion: "Hindu",
        religiion_in_guj: "હિન્દુ",
        caste: "Vaishnav",
        caste_in_guj: "વૈષ્ણવ",
        category: "OPEN",
        address: "78 Lakeview Society",
        district: "Vadodara",
        city: "Vadodara",
        state: "Gujarat",
        postal_code: 390002,
        bank_name: "ICICI Bank",
        account_no: 789012345678,
        IFSC_code: "ICIC0007890"
      },
      {
        id : 4,
        school_id : 1,
        staff_role_id: 3,
        first_name: "Rajesh",
        middle_name: "Manoj",
        last_name: "Chauhan",
        first_name_in_guj: "રાજેશ",
        middle_name_in_guj: "મનોજ",
        last_name_in_guj: "ચૌહાણ",
        gender: "Male",
        birth_date: new Date('1980-01-25'),
        mobile_number: 9090909090,
        email: "rajesh.chauhan@example.com",
        qualification: "M.Sc. Biology",
        subject_specialization: "Biology",
        class_id: 1,
        joining_date: new Date('2013-02-01'),
        employment_status: "Permanent",
        aadhar_no: 890123456789,
        religiion: "Hindu",
        religiion_in_guj: "હિન્દુ",
        caste: "Chauhan",
        caste_in_guj: "ચૌહાણ",
        category: "OBC",
        address: "56 Hill View Complex",
        district: "Rajkot",
        city: "Rajkot",
        state: "Gujarat",
        postal_code: 360002,
        bank_name: "Axis Bank",
        account_no: 890123456789,
        IFSC_code: "UTIB0008901"
      }
    ])
  }
}


