import OtherStaff from '#models/OtherStaff'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    // Write your database queries inside the run method
    OtherStaff.createMany(
      [
        {
          id : 1,
          school_id : 1,
          staff_role_id: 4, // Accountant
          first_name: "Nilesh",
          middle_name: "Kumar",
          last_name: "Patel",
          first_name_in_guj: "નિલેશ",
          middle_name_in_guj: "કુમાર",
          last_name_in_guj: "પટેલ",
          gender: "Male",
          birth_date: new Date("1985-03-15"),
          mobile_number: 9123456780,
          email: "nilesh.patel@example.com",
          joining_date: new Date("2015-06-20"),
          employment_status: "Permanent",
          aadhar_no: 123456789012,
          religiion: "Hindu",
          religiion_in_guj: "હિંદુ",
          caste: "Patel",
          caste_in_guj: "પટેલ",
          category: "OPEN",
          address: "123 Main Street",
          district: "Ahmedabad",
          city: "Ahmedabad",
          state: "Gujarat",
          postal_code: 380001,
          bank_name: "State Bank of India",
          account_no: 1234567890,
          IFSC_code: "SBIN0001234", 
        },
        {
          id : 2,
          school_id : 1,
          staff_role_id: 4, // Clerk
          first_name: "Rita",
          middle_name: "Kiran",
          last_name: "Desai",
          first_name_in_guj: "રીતા",
          middle_name_in_guj: "કિરણ",
          last_name_in_guj: "દેસાઈ",
          gender: "Female",
          birth_date: new Date("1992-05-10"),
          mobile_number: 9898981234,
          email: "rita.desai@example.com",
          joining_date: new Date("2019-09-15"),
          employment_status: "Trial_period",
          aadhar_no: 234567890123,
          religiion: "Jain",
          religiion_in_guj: "જૈન",
          caste: "Desai",
          caste_in_guj: "દેસાઈ",
          category: "OPEN",
          address: "456 Park Lane",
          district: "Surat",
          city: "Surat",
          state: "Gujarat",
          postal_code: 395003,
          bank_name: "HDFC Bank",
          account_no: 2345678901,
          IFSC_code: "HDFC0002345"
        },
        {
          id : 3,
          school_id : 1,
          staff_role_id: 5, // Librarian
          first_name: "Manoj",
          middle_name: "Ramesh",
          last_name: "Sharma",
          first_name_in_guj: "મનોજ",
          middle_name_in_guj: "રમેશ",
          last_name_in_guj: "શર્મા",
          gender: "Male",
          birth_date: new Date("1988-08-22"),
          mobile_number: 9876543210,
          email: "manoj.sharma@example.com",
          joining_date: new Date("2017-02-11"),
          employment_status: "Contact_base",
          aadhar_no: 345678901234,
          religiion: "Hindu",
          religiion_in_guj: "હિંદુ",
          caste: "Sharma",
          caste_in_guj: "શર્મા",
          category: "OPEN",
          address: "789 Market Road",
          district: "Vadodara",
          city: "Vadodara",
          state: "Gujarat",
          postal_code: 390001,
          bank_name: "ICICI Bank",
          account_no: 3456789012,
          IFSC_code: "ICIC0003456"
        },
        {
          id : 4,
          school_id : 1,
          staff_role_id: 6, // Peon
          first_name: "Bhavesh",
          middle_name: "Mohan",
          last_name: "Thakur",
          first_name_in_guj: "ભવેશ",
          middle_name_in_guj: "મોહન",
          last_name_in_guj: "ઠાકુર",
          gender: "Male",
          birth_date: new Date("1990-12-05"),
          mobile_number: 9999999999,
          email: "bhavesh.thakur@example.com",
          joining_date: new Date("2020-11-01"),
          employment_status: "Permanent",
          aadhar_no: 456789012345,
          religiion: "Hindu",
          religiion_in_guj: "હિંદુ",
          caste: "Thakur",
          caste_in_guj: "ઠાકુર",
          category: "OBC",
          address: "101 Village Road",
          district: "Rajkot",
          city: "Rajkot",
          state: "Gujarat",
          postal_code: 360001,
          bank_name: "Axis Bank",
          account_no: 4567890123,
          IFSC_code: "UTIB0004567"
        }
      ]
    )
  }
}